version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mytegroup-api
    restart: always
    ports:
      - "${API_PORT:-3000}:${APP_PORT:-3000}"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - APP_PORT=${APP_PORT}
      - PORT_DEV=${PORT_DEV}
      - PORT_PROD=${PORT_PROD}
      - APP_BASE_URL=${APP_BASE_URL}
      - CLIENT_BASE_URL=${CLIENT_BASE_URL}
      - CORS_ORIGINS_DEV=${CORS_ORIGINS_DEV}
      - CORS_ORIGINS_PROD=${CORS_ORIGINS_PROD}
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    command: npm run start:dev
    networks:
      - mytegroup-network

networks:
  mytegroup-network:
    driver: bridge

volumes: {}
